package enums;

public enum Move {
    THUNDERBOLT("Thunderbolt", PokemonType.ELECTRIC, 95, 100, 15, MoveType.SPECIAL, 0),
    LOVELYKISS("Lovely Kiss", PokemonType.NORMAL, 0, 75, 10, MoveType.STATUS, 0),
    DIG("Dig", PokemonType.GROUND, 100, 100, 10, MoveType.PHYSICAL, 0),
    THRASH("Thrash", PokemonType.NORMAL, 90, 100, 20, MoveType.PHYSICAL, 0),
    CONFUSERAY("Confuse Ray", PokemonType.GHOST, 0, 100, 10, MoveType.STATUS, 0),
    BUBBLE("Bubble", PokemonType.WATER, 20, 100, 30, MoveType.SPECIAL, 0),
    CUT("Cut", PokemonType.NORMAL, 50, 95, 30, MoveType.PHYSICAL, 0),
    RAGE("Rage", PokemonType.NORMAL, 20, 100, 20, MoveType.PHYSICAL, 0),
    RAGE("Rage", PokemonType.NORMAL, 1, 90, 10, MoveType.PHYSICAL, 0),
    STRINGSHOT("String Shot", PokemonType.BUG, 0, 95, 40, MoveType.STATUS, 0),
    SCREECH("Screech", PokemonType.NORMAL, 0, 85, 40, MoveType.STATUS, 0),
    ROCKTHROW("Rock Throw", PokemonType.ROCK, 50, 65, 15, MoveType.PHYSICAL, 0),
    ROCKSLIDE("Rock Slide", PokemonType.ROCK, 75, 90, 10, MoveType.PHYSICAL, 0),
    SING("Sing", PokemonType.NORMAL, 0, 55, 15, MoveType.STATUS, 0),
    SMOKESCREEN("Smokescreen", PokemonType.NORMAL, 0, 100, 20, MoveType.STATUS, 0),
    DOUBLESLAP("Double Slap", PokemonType.NORMAL, 15, 85, 10, MoveType.PHYSICAL, 0),
    MIRRORMOVE("Mirror Move", PokemonType.FLYING, 0, 0, 20, MoveType.STATUS, 0),
    AURORABEAM("Aurora Beam", PokemonType.ICE, 65, 100, 20, MoveType.SPECIAL, 0),
    STRENGTH("Strength", PokemonType.NORMAL, 80, 100, 15, MoveType.PHYSICAL, 0),
    COUNTER("Counter", PokemonType.FIGHTING, 1, 100, 20, MoveType.PHYSICAL, -1),
    FLAMETHROWER("Flamethrower", PokemonType.FIRE, 95, 100, 15, MoveType.SPECIAL, 0),
    SHARPEN("Sharpen", PokemonType.NORMAL, 0, 0, 30, MoveType.STATUS, 0),
    DOUBLETEAM("Double Team", PokemonType.NORMAL, 0, 0, 30, MoveType.STATUS, 0),
    GUST("Gust", PokemonType.FLYING, 40, 100, 35, MoveType.SPECIAL, 0),
    HARDEN("Harden", PokemonType.NORMAL, 0, 0, 30, MoveType.STATUS, 0),
    DISABLE("Disable", PokemonType.NORMAL, 0, 55, 20, MoveType.STATUS, 0),
    RAZORWIND("Razor Wind", PokemonType.NORMAL, 80, 75, 10, MoveType.SPECIAL, 0),
    ENDURE("Endure", PokemonType.NORMAL, 0, 0, 10, MoveType.STATUS, 0),
    BITE("Bite", PokemonType.NORMAL, 60, 100, 25, MoveType.PHYSICAL, 0),
    THUNDER("Thunder", PokemonType.ELECTRIC, 120, 70, 10, MoveType.SPECIAL, 0),
    THUNDERPUNCH("Thunder Punch", PokemonType.ELECTRIC, 75, 100, 15, MoveType.PHYSICAL, 0),
    KARATECHOP("Karate Chop", PokemonType.FIGHTING, 50, 100, 25, MoveType.PHYSICAL, 0),
    VICEGRIP("Vice Grip", PokemonType.NORMAL, 55, 100, 30, MoveType.PHYSICAL, 0),
    WITHDRAW("Withdraw", PokemonType.WATER, 0, 0, 40, MoveType.STATUS, 0),
    CONSTRICT("Constrict", PokemonType.NORMAL, 10, 100, 35, MoveType.PHYSICAL, 0),
    FOCUSENERGY("Focus Energy", PokemonType.NORMAL, 0, 0, 30, MoveType.STATUS, 0),
    SPORE("Spore", PokemonType.GRASS, 0, 100, 15, MoveType.STATUS, 0),
    LEECHLIFE("Leech Life", PokemonType.BUG, 20, 100, 15, MoveType.PHYSICAL, 0),
    SLASH("Slash", PokemonType.NORMAL, 70, 100, 20, MoveType.PHYSICAL, 0),
    CRABHAMMER("Crabhammer", PokemonType.WATER, 90, 85, 10, MoveType.SPECIAL, 0),
    HAZE("Haze", PokemonType.ICE, 0, 0, 30, MoveType.STATUS, 0),
    LOWKICK("Low Kick", PokemonType.FIGHTING, 0, 100, 20, MoveType.PHYSICAL, 0),
    AGILITY("Agility", PokemonType.PSYCHIC, 0, 0, 30, MoveType.STATUS, 0),
    SKYATTACK("Sky Attack", PokemonType.FLYING, 140, 90, 5, MoveType.PHYSICAL, 0),
    PSYBEAM("Psybeam", PokemonType.PSYCHIC, 65, 100, 20, MoveType.SPECIAL, 0),
    PSYWAVE("Psywave", PokemonType.PSYCHIC, 1, 80, 15, MoveType.SPECIAL, 0),
    PSYCHIC("Psychic", PokemonType.PSYCHIC, 90, 100, 10, MoveType.SPECIAL, 0),
    HYPNOSIS("Hypnosis", PokemonType.PSYCHIC, 0, 60, 20, MoveType.STATUS, 0),
    WHEELOFFIRE("Wheel of Fire", PokemonType.NORMAL, 0, 0, 30, MoveType.STATUS, 0),
    RECOVER("Recover", PokemonType.NORMAL, 0, 0, 20, MoveType.STATUS, 0),
    EARTHQUAKE("Earthquake", PokemonType.GROUND, 100, 100, 10, MoveType.PHYSICAL, 0),
    LICK("Lick", PokemonType.GHOST, 20, 100, 30, MoveType.PHYSICAL, 0),
    TAILWHIP("Tail Whip", PokemonType.NORMAL, 0, 100, 30, MoveType.STATUS, 0),
    SELFDESTRUCT("Self-Destruct", PokemonType.NORMAL, 130, 100, 5, MoveType.PHYSICAL, 0),
    STUNSPORE("Stun Spore", PokemonType.GRASS, 0, 75, 30, MoveType.STATUS, 0),
    BIND("Bind", PokemonType.NORMAL, 15, 85, 20, MoveType.PHYSICAL, 0),
    HAZE("Haze", PokemonType.ICE, 0, 0, 30, MoveType.STATUS, 0),
    FISSURE("Fissure", PokemonType.GROUND, 1, 30, 5, MoveType.PHYSICAL, 0),
    ABSORB("Absorb", PokemonType.GRASS, 20, 100, 15, MoveType.SPECIAL, 0),
    HEADBUTT("Headbutt", PokemonType.NORMAL, 70, 100, 20, MoveType.PHYSICAL, 0),
    TAKEDOWN("Take Down", PokemonType.NORMAL, 90, 85, 20, MoveType.PHYSICAL, 0),
    SANDATTACK("Sand Attack", PokemonType.NORMAL, 0, 100, 15, MoveType.STATUS, 0),
    SWIFT("Swift", PokemonType.NORMAL, 60, 100, 20, MoveType.SPECIAL, 0),
    KINESIS("Kinesis", PokemonType.PSYCHIC, 0, 80, 15, MoveType.STATUS, 0),
    SMOG("Smog", PokemonType.POISON, 20, 70, 20, MoveType.PHYSICAL, 0),
    GROWTH("Growth", PokemonType.NORMAL, 0, 0, 20, MoveType.STATUS, 0),
    SOLARBEAM("Solar Beam", PokemonType.GRASS, 120, 100, 10, MoveType.SPECIAL, 0),
    SONICBOOM("Sonic Boom", PokemonType.NORMAL, 1, 90, 20, MoveType.SPECIAL, 0),
    FLY("Fly", PokemonType.FLYING, 70, 95, 15, MoveType.PHYSICAL, 0),
    TACKLE("Tackle", PokemonType.NORMAL, 40, 100, 35, MoveType.PHYSICAL, 0),
    EXPLOSION("Explosion", PokemonType.NORMAL, 170, 100, 5, MoveType.PHYSICAL, 0),
    FIREBLAST("Fire Blast", PokemonType.FIRE, 120, 85, 5, MoveType.SPECIAL, 0),
    CLIMBWATERFALL("Climb Waterfall", PokemonType.WATER, 80, 100, 15, MoveType.SPECIAL, 0),
    BEAT("Beat", PokemonType.NORMAL, 100, 100, 15, MoveType.PHYSICAL, 0),
    DOUBLENEEDLE("Double Needle", PokemonType.BUG, 25, 100, 20, MoveType.PHYSICAL, 0),
    EGGLAY("Egg Lay", PokemonType.NORMAL, 0, 0, 10, MoveType.STATUS, 0),
    EGGBOMB("Egg Bomb", PokemonType.NORMAL, 100, 75, 10, MoveType.PHYSICAL, 0),
    THROW("Throw", PokemonType.NORMAL, 15, 85, 20, MoveType.PHYSICAL, 0),
    MINIMIZE("Minimize", PokemonType.NORMAL, 0, 0, 20, MoveType.STATUS, 0),
    SEISMICTOSS("Seismic Toss", PokemonType.FIGHTING, 1, 100, 20, MoveType.PHYSICAL, 0),
    SUPERSONIC("Supersonic", PokemonType.NORMAL, 0, 55, 20, MoveType.STATUS, 0),
    PECK("Peck", PokemonType.FLYING, 35, 100, 35, MoveType.PHYSICAL, 0),
    DRILL("Drill", PokemonType.NORMAL, 70, 100, 20, MoveType.PHYSICAL, 0),
    WINGATTACK("Wing Attack", PokemonType.FLYING, 65, 100, 25, MoveType.PHYSICAL, 0),
    SWORDSDANCE("Swords Dance", PokemonType.NORMAL, 0, 0, 30, MoveType.STATUS, 0),
    WHIPVINE("Whip Vine", PokemonType.GRASS, 0, 0, 30, MoveType.STATUS, 0),
    CAMOUFLAGE("Camouflage", PokemonType.NORMAL, 0, 0, 20, MoveType.STATUS, 0),
    TELEPORT("Teleport", PokemonType.PSYCHIC, 0, 0, 20, MoveType.STATUS, 0),
    ELECTRICSHOCK("Electric Shock", PokemonType.ELECTRIC, 40, 100, 30, MoveType.SPECIAL, 0),
    QUICKATTACK("Quick Attack", PokemonType.NORMAL, 40, 100, 30, MoveType.PHYSICAL, 1),
    THUNDERWAVE("Thunder Wave", PokemonType.ELECTRIC, 0, 90, 20, MoveType.STATUS, 0),
    POISONGAS("Poison Gas", PokemonType.POISON, 0, 55, 40, MoveType.STATUS, 0),
    TOXIC("Toxic", PokemonType.POISON, 0, 85, 10, MoveType.STATUS, 0),
    POISONPOWDER("Poison Powder", PokemonType.POISON, 0, 75, 35, MoveType.STATUS, 0),
    POISONSTING("Poison Sting", PokemonType.POISON, 15, 100, 35, MoveType.PHYSICAL, 0),
    SPIKECANNON("Spike Cannon", PokemonType.NORMAL, 20, 100, 15, MoveType.PHYSICAL, 0),
    MELT("Melt", PokemonType.ICE, 0, 0, 40, MoveType.STATUS, 0),
    CHARGE("Charge", PokemonType.ELECTRIC, 0, 0, 20, MoveType.STATUS, 0),
    FLYINGKICK("Flying Kick", PokemonType.FIGHTING, 60, 85, 15, MoveType.PHYSICAL, 0),
    JUMPKICK("Jump Kick", PokemonType.FIGHTING, 70, 95, 25, MoveType.PHYSICAL, 0),
    TRIATTACK("Tri Attack", PokemonType.NORMAL, 80, 100, 10, MoveType.SPECIAL, 0),
    DRILLPECK("Drill Peck", PokemonType.FLYING, 80, 100, 20, MoveType.PHYSICAL, 0),
    AMNESIA("Amnesia", PokemonType.PSYCHIC, 0, 0, 30, MoveType.STATUS, 0),
    NIGHTSHADE("Night Shade", PokemonType.GHOST, 1, 100, 15, MoveType.SPECIAL, 0),
    SURF("Surf", PokemonType.WATER, 95, 100, 15, MoveType.SPECIAL, 0),
    DOUBLEKICK("Double Kick", PokemonType.FIGHTING, 30, 100, 30, MoveType.PHYSICAL, 0),
    GLARE("Glare", PokemonType.NORMAL, 0, 100, 30, MoveType.STATUS, 0),
    COINFORCATS("Coin for Cats", PokemonType.NORMAL, 0, 0, 30, MoveType.STATUS, 0),
    SLEEPSPORE("Sleep Spore", PokemonType.GRASS, 0, 75, 30, MoveType.STATUS, 0),
    SLEEP("Sleep", PokemonType.PSYCHIC, 0, 0, 10, MoveType.STATUS, 0),
    PSYCHIC("Psychic", PokemonType.PSYCHIC, 90, 100, 10, MoveType.SPECIAL, 0),
    CRUSH("Crush", PokemonType.NORMAL, 0, 0, 20, MoveType.STATUS, 0),
    HYDROPUMP("Hydro Pump", PokemonType.WATER, 120, 80, 5, MoveType.SPECIAL, 0),
    HYPERBEAM("Hyper Beam", PokemonType.NORMAL, 150, 90, 5, MoveType.SPECIAL, 0),
    GUILLOTINE("Guillotine", PokemonType.NORMAL, 1, 30, 5, MoveType.PHYSICAL, 0),
    PINCER("Pincer", PokemonType.BUG, 55, 100, 30, MoveType.PHYSICAL, 0),
    SLAP("Slap", PokemonType.NORMAL, 40, 100, 35, MoveType.PHYSICAL, 0),
    RAZORLEAF("Razor Leaf", PokemonType.GRASS, 55, 95, 25, MoveType.PHYSICAL, 0),
    PETALDANCE("Petal Dance", PokemonType.GRASS, 70, 100, 20, MoveType.SPECIAL, 0),
    BOUNCE("Bounce", PokemonType.FLYING, 85, 85, 20, MoveType.PHYSICAL, 0),
    BUBBLEBEAM("Bubble Beam", PokemonType.WATER, 65, 100, 20, MoveType.SPECIAL, 0),
    BARRIER("Barrier", PokemonType.PSYCHIC, 0, 0, 30, MoveType.STATUS, 0),
    LIGHTSCREEN("Light Screen", PokemonType.PSYCHIC, 0, 0, 30, MoveType.STATUS, 0),
    SCRATCH("Scratch", PokemonType.NORMAL, 40, 100, 35, MoveType.PHYSICAL, 0),
    CRITICALBITE("Critical Bite", PokemonType.NORMAL, 0, 0, 20, MoveType.STATUS, 0),
    EMBER("Ember", PokemonType.FIRE, 40, 100, 25, MoveType.SPECIAL, 0),
    PIYOPIYOPUNCH("Piyo Piyo Punch", PokemonType.NORMAL, 20, 100, 30, MoveType.PHYSICAL, 0),
    WHIRLWIND("Whirlwind", PokemonType.NORMAL, 0, 0, 20, MoveType.STATUS, 0),
    BLIZZARD("Blizzard", PokemonType.ICE, 120, 70, 5, MoveType.SPECIAL, 0),
    STOMP("Stomp", PokemonType.NORMAL, 65, 100, 20, MoveType.PHYSICAL, 0),
    FLASH("Flash", PokemonType.NORMAL, 0, 70, 20, MoveType.STATUS, 0),
    SLUDGEATTACK("Sludge Attack", PokemonType.POISON, 65, 100, 20, MoveType.PHYSICAL, 0),
    GLARE("Glare", PokemonType.NORMAL, 0, 100, 30, MoveType.STATUS, 0),
    TRANSFORM("Transform", PokemonType.NORMAL, 0, 0, 10, MoveType.STATUS, 0),
    HOWL("Howl", PokemonType.NORMAL, 0, 0, 30, MoveType.STATUS, 0),
    BONECLUB("Bone Club", PokemonType.GROUND, 65, 85, 20, MoveType.PHYSICAL, 0),
    BONEBOOMERANG("Bone Boomerang", PokemonType.GROUND, 50, 90, 10, MoveType.PHYSICAL, 0),
    FIREWHIRLPOOL("Fire Whirlpool", PokemonType.FIRE, 15, 70, 15, MoveType.SPECIAL, 0),
    FIREPUNCH("Fire Punch", PokemonType.FIRE, 75, 100, 15, MoveType.SPECIAL, 0),
    WRAPAROUND("Wraparound", PokemonType.NORMAL, 0, 0, 40, MoveType.STATUS, 0),
    ROUND("Round", PokemonType.NORMAL, 0, 0, 30, MoveType.STATUS, 0),
    SPINNINGKICK("Spinning Kick", PokemonType.NORMAL, 0, 0, 20, MoveType.STATUS, 0),
    SUBSTITUTE("Substitute", PokemonType.NORMAL, 0, 0, 10, MoveType.STATUS, 0),
    MISSILENEEDLE("Missile Needle", PokemonType.BUG, 25, 95, 20, MoveType.PHYSICAL, 0),
    WATERGUN("Water Gun", PokemonType.WATER, 40, 100, 25, MoveType.SPECIAL, 0),
    MADPUNCH("Mud Punch", PokemonType.GROUND, 20, 100, 10, MoveType.PHYSICAL, 0),
    MADSCRATCH("Mud Scratch", PokemonType.GROUND, 20, 100, 15, MoveType.PHYSICAL, 0),
    MEGADRAIN("Mega Drain", PokemonType.GRASS, 40, 100, 10, MoveType.SPECIAL, 0),
    MEGAKICK("Mega Kick", PokemonType.NORMAL, 120, 75, 5, MoveType.PHYSICAL, 0),
    MEGAPUNCH("Mega Punch", PokemonType.NORMAL, 80, 85, 20, MoveType.PHYSICAL, 0),
    MIMIC("Mimic", PokemonType.NORMAL, 0, 0, 10, MoveType.STATUS, 0),
    MISTLETOESEED("Mistletoe Seed", PokemonType.GRASS, 0, 0, 10, MoveType.STATUS, 0),
    WAGFINGER("Wag Finger", PokemonType.NORMAL, 0, 0, 10, MoveType.STATUS, 0),
    DREAMEATER("Dream Eater", PokemonType.PSYCHIC, 100, 100, 15, MoveType.SPECIAL, 0),
    ACID("Acid", PokemonType.POISON, 40, 100, 30, MoveType.SPECIAL, 0),
    YOGAPOSE("Yoga Pose", PokemonType.PSYCHIC, 0, 0, 40, MoveType.STATUS, 0),
    REFLECTOR("Reflector", PokemonType.PSYCHIC, 0, 0, 20, MoveType.STATUS, 0),
    DRAGONRAGE("Dragon Rage", PokemonType.DRAGON, 1, 100, 10, MoveType.SPECIAL, 0),
    ICEPUNCH("Ice Punch", PokemonType.ICE, 75, 100, 15, MoveType.SPECIAL, 0),
    ICEBEAM("Ice Beam", PokemonType.ICE, 95, 100, 10, MoveType.SPECIAL, 0),
    CONTINUOUSPUNCH("Continuous Punch", PokemonType.NORMAL, 0, 0, 20, MoveType.STATUS, 0),
    ROCKETHEADBUTT("Rocket Headbutt", PokemonType.NORMAL, 0, 0, 30, MoveType.STATUS, 0),
    STRUGGLE("Struggle", PokemonType.NORMAL, 50, 100, 1, MoveType.PHYSICAL, 0);

    private final String moveName;
    private final PokemonType moveType;
    private final int pwr;
    private final int acc;
    private final int pp;
    private final MoveType species;
    private final int priority;

    Move(String moveName, PokemonType moveType, int pwr, int acc, int pp, MoveType species, int priority) {
        this.moveName = moveName;
        this.moveType = moveType;
        this.pwr = pwr;
        this.acc = acc;
        this.pp = pp;
        this.species = species;
        this.priority = priority;
    }
}
